version: '3.1'

services:
  web:
    build:
      dockerfile: ./scripts/php74-apache.dockerfile
      context: .
    ports:
      - "80:80"
    volumes:
      - ./../:/var/www/html/
      # - ./scripts/php.ini:/usr/local/etc/php/php.ini
    links:
      - mariadb
  mariadb:
    image: mariadb:10.6.16
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=@2024#Mariadb!
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=@Admin!2024@Sga
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - mariadb